# Generated by Django 5.0.3 on 2024-03-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprodutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='capa',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
