# Generated by Django 5.0.3 on 2024-03-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprodutor', '0003_alter_musica_audio_alter_musica_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='artista',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
